version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-!3!xi5c73=r7xg^7w8+qs8lp=bkklm*a%258#%xdzkvw*o#5mu
      - DATABASE_URL=postgres://postgres:watermelonIce@db:5432/mngdb

  db:
    image: postgres
    environment:
      POSTGRES_DB: mngdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: watermelonIce
