# Generated by Django 5.0 on 2024-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_status_historicallisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='new', max_length=10),
        ),
    ]
